language: cpp
sudo: required
dist: xenial

os:
 - linux
 - osx

before_install: 
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    sudo add-apt-repository ppa:beineri/opt-qt-5.15.0-xenial -y;
    sudo apt-get update -qq;
    fi

#MAC OS
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew update > /dev/null;
    fi

install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo apt-get -y install build-essential qt5-default qt515tools qt515base qt515translations qt515imageformats g++-8 zsync;
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90;
    source /opt/qt*/bin/qt*-env.sh;
    fi

#MAC OS
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew upgrade qt;
    chmod -R 755 /usr/local/opt/qt5/*;
    fi


script:

- if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    qmake Hyne.pro;
    make -j4;
    make INSTALL_ROOT=appdir install; find appdir/;
    mv appdir/usr/share/hyne/*.qm appdir/usr/bin;
    rm -rf appdir/usr/share/hyne appdir/usr/share/menu;
    wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
    chmod a+x linuxdeployqt*.AppImage;
    unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH;
    export VERSION=continuous;
    ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage;
    fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    export QTDIR="/usr/local/opt/qt5";
    export PATH="$QTDIR/bin:$PATH";
    qmake Hyne.pro;
    make -j4;
    mv *.qm Hyne.app/Contents/MacOS/;
    cp /usr/lib/libz.dylib Hyne.app/Contents/MacOS/;
    macdeployqt Hyne.app/ -dmg;
    fi

after_success:
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq ;
    bash ./upload.sh Hyne*.AppImage*;
    fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    mv Hyne*.dmg* Hyne-continuous*.dmg*;
    bash ./upload.sh Hyne*.dmg*;
    fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
